uploadImage:
  handler: src/handlers/uploadImage.handler
  events:
    - http:
        path: /upload
        method: POST
        cors:
          origins:
            - 'http://localhost:5173'
        # authorizer:
        #   type: COGNITO_USER_POOLS
        #   authorizerId:
        #     Ref: ApiGatewayAuthorizer
analyzeImage:
  handler: src/handlers/analyzeImage.handler
  events:
    - http:
        path: /analyze/{key}
        method: GET
        cors:
          origins:
            - 'http://localhost:5173'
        # authorizer:
        #   type: COGNITO_USER_POOLS
        #   authorizerId:
        #     Ref: ApiGatewayAuthorizer
