Type: AWS::S3::BucketPolicy
Properties:
  Bucket: !Ref TrackaPetsBucket
  PolicyDocument:
    Statement:
      - Sid: PublicRead
        Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource: arn:aws:s3:::${self:custom.ImageAnalysisBucket.name}/*
        Condition:
          Bool:
            aws:SecureTransport: 'true'
