Type: AWS::S3::Bucket
Properties:
  BucketName: ${self:custom.ImageAnalysisBucket.name}
  PublicAccessBlockConfiguration:
    BlockPublicAcls: true
    BlockPublicPolicy: true
    IgnorePublicAcls: true
    RestrictPublicBuckets: true
